Fix prolog issues
IASI-SAKS/hyperion pull request #4
Opened 2020-12-01 22:11 UTC by alessandropellegrini

Prolog issues should be fixed now.

Also, logs use a timestamp in the name. Logs useful for testing are stored in `./src/main/test/resources/`

2020-12-02 09:27 UTC, emadea requested changes
- There are a few occurrences of 0L that should be replaced by '0L' 
https://github.com/IASI-SAKS/hyperion/blob/84d187973d4bb16a00f7347f9c6b83b668244b64/src/test/resources/inspection.datalog#L221
(see also lines 222, 225, 226, 282, 283, 286, 287)

- I would change the file extension from '.datalog' to '.pl'

2020-12-02 09:46 UTC, alessandropellegrini commented
Yes, that's the previous file, which I included for historical purposes but that can be removed. The new one is `src/test/resources/inspection-2020-12-01T22:01Z.datalog`. Does it work?

2020-12-03 11:00 UTC, gulyx approved these changes
fine

2020-12-03 11:00 UTC, emadea approved these changes

2020-12-03 11:01 UTC, merged